# -*- coding: utf-8 -*-
"""gnlp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A4Saisu4KPTPgAxY3VJ-lGQ8gYEQHubI
"""

import pandas as pd
import csv

header = ['videoid', 'segmentid', 'text']


with open('preprocess.csv', 'w', encoding='UTF8', newline='') as f:
     writer = csv.writer(f)

     # write the header
     writer.writerow(header)

     # write the data
     file1 = open('text.id.en', 'r')
     Lines = file1.readlines()

     count = 0
      # Strips the newline character
     for line in Lines:
        data=[]
        count += 1
        line = str(line)
        videoid = line[2:11]
        segmentnumber = line.split()[0].split('_')[len(line.split()[0].split('_'))-1]
        captions = line.split()[1:]
        data = [videoid, segmentnumber,captions]
        writer.writerow(data)
        #print(data)
     file1.close()


df= pd.read_csv("preprocess.csv")

df.head

import csv
import pandas as pd

header = ['videoid', 'segmentid', 'timestamp']


with open('withtime.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)

    # write the header
    writer.writerow(header)

    file1 = open('/content/segments', 'r')
    Lines = file1.readlines()

    count = 0
    df2 = pd.read_csv('preprocess.csv')
    # Strips the newline character
    for line in Lines:
        data=[]
        count += 1
        line = str(line)
        videoid = line[2:11]
        segmentnumber = line.split()[0].split('_')[len(line.split()[0].split('_'))-1]
        time = [line.split()[2], line.split()[3]]
        #print(time)
        #print(videoid, segmentnumber)
        data = [videoid, segmentnumber, time]
        print(data)
        writer.writerow(data)
    # df2.to_csv("withtimestamp.csv")
    # df2 =  pd.read_csv('withtimestamp.csv')
    # df2

file1.close()

# df= pd.read_csv("withtime.csv")

# df.head

cols = ['videoid', 'segmentid']
df1 = pd.read_csv("preprocess.csv")
df2 = pd.read_csv("withtime.csv")
dfs = [df1, df2]
df_merged = pd.concat([x.set_index(cols) for x in dfs], axis=1)    
df_merged.to_csv('merged.csv', sep=',', encoding='utf-8')

from scipy.io import wavfile
import moviepy.editor
import cv2


filename = 'merged.csv'

with open(filename, 'w') as csvfile:
    datareader = csv.reader(csvfile)
    for row in datareader:
      # read the file and get the sample rate and data
      video_name = row 
      vidcap = cv2.VideoCapture(video_name)

      success,image = vidcap.read()
      vidcap.set(0,(row['timestamp'][1]-row['timestamp'][0])/2);
      ret, frame = vidcap.read() 
      cv2.imshow('window_name', frame)
      row['image'] = frame

      video = moviepy.editor.VideoFileClip(row['videoid'])#change to include full path under subs directory 

      audio = video.audio   
      rate, data = wavfile.read(audio) 
      # the timestamp to split at (in seconds)
      split_at_timestamp = row['timestamp']

      # get the frame to split at
      split_at_frame_start = rate * split_at_timestamp[0]
      split_at_frame_end = rate * split_at_timestamp[1]
      

      # split
      clip = data[split_at_frame_start:split_at_frame_end-1] # split

      wavfile.write('clip.wav', rate, clip)
      row["audio"] = 'clip.wav' #make sure path is to what wavfile writes to